version: '3.8'

services:
  ponto-eletronico-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ponto-eletronico-api:latest
    container_name: ponto-eletronico-api
    ports:
      - "8080:8080"
    env_file:
      - ./DeltaFour.API/.env
    volumes:
      - C:\deltafour-495323-b36ef3f96064.json:/secrets/gcs-key.json:ro
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - delta-net

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - ./DeltaFour.API/.env
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p12345678"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 30s
    networks:
      - delta-net

volumes:
  mysql-data:

networks:
  delta-net:
    external: true
