// <auto-generated />
using System;
using DeltaFour.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace DeltaFour.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607120900_CentroidFeaturesToDouble")]
    partial class CentroidFeaturesToDouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DeltaFour.Domain.Entities.Action", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("action", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd3eeccb-1501-48fc-9865-b04cf06b7eed"),
                            Name = "list"
                        },
                        new
                        {
                            Id = new Guid("dbc8f1c2-13ef-468b-8b0d-5ec47a223dee"),
                            Name = "create"
                        },
                        new
                        {
                            Id = new Guid("0040c417-becf-4f7e-a15c-488879583095"),
                            Name = "update"
                        },
                        new
                        {
                            Id = new Guid("22cd6eba-64a8-4283-afe4-9a5acb278fd2"),
                            Name = "delete"
                        });
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("city");

                    b.Property<string>("Complement")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("complement");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("district");

                    b.Property<int?>("Number")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("street");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.ClusterCentroid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<double>("AverageLateMinutes")
                        .HasColumnType("double")
                        .HasColumnName("average_late_minutes");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("calculated_at");

                    b.Property<int>("Cluster")
                        .HasColumnType("int")
                        .HasColumnName("cluster");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<double>("LatePercentage")
                        .HasColumnType("double")
                        .HasColumnName("late_percentage");

                    b.Property<double>("MaxLateMinutes")
                        .HasColumnType("double")
                        .HasColumnName("max_late_minutes");

                    b.Property<double>("TotalAbsences")
                        .HasColumnType("double")
                        .HasColumnName("total_absences");

                    b.Property<double>("TotalWorkedDays")
                        .HasColumnType("double")
                        .HasColumnName("total_worked_days");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Cluster");

                    b.ToTable("cluster_centroids", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)")
                        .HasColumnName("address_id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 707, DateTimeKind.Utc).AddTicks(2248))
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.CompanyGeolocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<Point>("Coord")
                        .IsRequired()
                        .HasColumnType("point")
                        .HasColumnName("coord");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("int")
                        .HasColumnName("radius_meters");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("company_geolocation", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 708, DateTimeKind.Utc).AddTicks(8005))
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("location", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("86e2ff65-f489-43a4-8b73-b55d7791206c"),
                            Name = "company"
                        },
                        new
                        {
                            Id = new Guid("19a4c512-6fb8-4470-a69f-1a523bef393e"),
                            Name = "employee"
                        },
                        new
                        {
                            Id = new Guid("15a63d83-f349-44de-a2e3-de287e119ece"),
                            Name = "work"
                        });
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 709, DateTimeKind.Utc).AddTicks(6570))
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Code")
                        .HasDatabaseName("IX_password_reset_tokens_user_id_code");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 710, DateTimeKind.Utc).AddTicks(851))
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("action_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("location_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 711, DateTimeKind.Utc).AddTicks(389))
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("plan_name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.SubscriptionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 711, DateTimeKind.Utc).AddTicks(5297))
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("subscription_events", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 712, DateTimeKind.Utc).AddTicks(3913))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EmployeeSignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("employee_signed_at");

                    b.Property<DateTime?>("HRSignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hr_signed_at");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<bool>("SignedByEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("signed_by_employee");

                    b.Property<bool>("SignedByHR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("signed_by_hr");

                    b.Property<Guid?>("SignedByHRUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("signed_by_hr_user_id");

                    b.Property<string>("SignedByHRUserName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("signed_by_hr_user_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_time_sheet_user_month_year");

                    b.ToTable("time_sheet", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheetAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 711, DateTimeKind.Utc).AddTicks(8657))
                        .HasColumnName("created_at");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("operation");

                    b.Property<Guid>("TimeSheetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("time_sheet_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("TimeSheetId");

                    b.ToTable("time_sheet_audits", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheetSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 712, DateTimeKind.Utc).AddTicks(8729))
                        .HasColumnName("created_at");

                    b.Property<DateTime>("SignedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("signed_at_utc");

                    b.Property<string>("SignerCpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("signer_cpf");

                    b.Property<string>("SignerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("signer_email");

                    b.Property<string>("SignerIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("signer_ip");

                    b.Property<string>("SignerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("signer_name");

                    b.Property<string>("SignerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("signer_type");

                    b.Property<Guid>("SignerUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("signer_user_id");

                    b.Property<string>("TimeSheetHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("time_sheet_hash");

                    b.Property<Guid>("TimeSheetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("time_sheet_id");

                    b.HasKey("Id");

                    b.HasIndex("TimeSheetId");

                    b.ToTable("time_sheet_signatures", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheetSignatureToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 713, DateTimeKind.Utc).AddTicks(2907))
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("SignerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("signer_type");

                    b.Property<Guid>("SignerUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("signer_user_id");

                    b.Property<Guid>("TimeSheetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("time_sheet_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("used_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TimeSheetId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_time_sheet_signature_tokens_token");

                    b.ToTable("time_sheet_signature_tokens", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Cellphone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cellphone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 23, 57, 28, 714, DateTimeKind.Utc).AddTicks(8061))
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAllowedBypassCoord")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_allowed_by_pass_coord");

                    b.Property<bool>("IsAllowedBypassFacial")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_allowed_bypass_facial");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_confirmed");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Point>("Coord")
                        .IsRequired()
                        .HasColumnType("point")
                        .HasColumnName("coord");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<bool>("IsLate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_late");

                    b.Property<string>("Justification")
                        .HasColumnType("longtext")
                        .HasColumnName("justification");

                    b.Property<string>("Observation")
                        .HasColumnType("longtext")
                        .HasColumnName("observation");

                    b.Property<DateTime>("PunchTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("punch_time");

                    b.Property<string>("PunchType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("punch_type");

                    b.Property<int>("ShiftType")
                        .HasColumnType("int")
                        .HasColumnName("shift_type");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<TimeOnly?>("TimeLate")
                        .HasColumnType("time(6)")
                        .HasColumnName("time_late");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_attendance", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserAuth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("refresh_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_auth", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("FaceTemplate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_face", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserPunctualityMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<double>("AverageLateMinutes")
                        .HasColumnType("double")
                        .HasColumnName("average_late_minutes");

                    b.Property<int?>("Cluster")
                        .HasColumnType("int")
                        .HasColumnName("cluster");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_calculated_at");

                    b.Property<double>("LatePercentage")
                        .HasColumnType("double")
                        .HasColumnName("late_percentage");

                    b.Property<int>("MaxLateMinutes")
                        .HasColumnType("int")
                        .HasColumnName("max_late_minutes");

                    b.Property<int>("TotalAbsences")
                        .HasColumnType("int")
                        .HasColumnName("total_absences");

                    b.Property<int>("TotalAttendances")
                        .HasColumnType("int")
                        .HasColumnName("total_attendances");

                    b.Property<int>("TotalLateAttendances")
                        .HasColumnType("int")
                        .HasColumnName("total_late_attendances");

                    b.Property<int>("TotalWorkedDays")
                        .HasColumnType("int")
                        .HasColumnName("total_worked_days");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_punctuality_metrics", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("char(36)")
                        .HasColumnName("shift_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("user_shift", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.WorkShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shift_type");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("starter_time");

                    b.Property<int>("ToleranceMinutes")
                        .HasColumnType("int")
                        .HasColumnName("tolerance_minutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("work_shift", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.ClusterCentroid", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Company", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Address", "Address")
                        .WithOne("Company")
                        .HasForeignKey("DeltaFour.Domain.Entities.Company", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.CompanyGeolocation", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithOne("CompanyGeolocation")
                        .HasForeignKey("DeltaFour.Domain.Entities.CompanyGeolocation", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Department", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Role", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Action", "Action")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeltaFour.Domain.Entities.Location", "Location")
                        .WithMany("RolePermissions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeltaFour.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Location");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithOne("Subscription")
                        .HasForeignKey("DeltaFour.Domain.Entities.Subscription", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.SubscriptionEvent", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionEvents")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheet", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheetAudit", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.TimeSheet", "TimeSheet")
                        .WithMany("Audits")
                        .HasForeignKey("TimeSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeSheet");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheetSignature", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.TimeSheet", "TimeSheet")
                        .WithMany("Signatures")
                        .HasForeignKey("TimeSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeSheet");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheetSignatureToken", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.TimeSheet", "TimeSheet")
                        .WithMany("SignatureTokens")
                        .HasForeignKey("TimeSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeSheet");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.User", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithMany("User")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeltaFour.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DeltaFour.Domain.Entities.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId");

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserAttendance", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithMany("UserAttendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserAuth", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithOne("UserAuth")
                        .HasForeignKey("DeltaFour.Domain.Entities.UserAuth", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserFace", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithMany("UserFaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserPunctualityMetric", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("DeltaFour.Domain.Entities.UserPunctualityMetric", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserShift", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.WorkShift", "WorkShift")
                        .WithMany("UserShifts")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithMany("UserShifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.WorkShift", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithMany("WorkShifts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Action", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Address", b =>
                {
                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Company", b =>
                {
                    b.Navigation("CompanyGeolocation");

                    b.Navigation("Roles");

                    b.Navigation("Subscription");

                    b.Navigation("User");

                    b.Navigation("WorkShifts");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Location", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("SubscriptionEvents");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheet", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("SignatureTokens");

                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.User", b =>
                {
                    b.Navigation("UserAttendances");

                    b.Navigation("UserAuth");

                    b.Navigation("UserFaces");

                    b.Navigation("UserShifts");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.WorkShift", b =>
                {
                    b.Navigation("UserShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
