// <auto-generated />
using System;
using DeltaFour.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace DeltaFour.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521112822_AddTimeSheetTable")]
    partial class AddTimeSheetTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DeltaFour.Domain.Entities.Action", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("action", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("432aa524-15f6-4995-8aa3-36d7dc8ad2e5"),
                            Name = "list"
                        },
                        new
                        {
                            Id = new Guid("b3b9322f-c361-4254-ae00-20eeddb8698a"),
                            Name = "create"
                        },
                        new
                        {
                            Id = new Guid("71e2c264-4e0b-4f77-88ab-e6ba5290a5bf"),
                            Name = "update"
                        },
                        new
                        {
                            Id = new Guid("190deee0-6846-47b2-b128-cf8e82f86337"),
                            Name = "delete"
                        });
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("district");

                    b.Property<int?>("Number")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("street");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)")
                        .HasColumnName("address_id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 5, 21, 11, 28, 22, 36, DateTimeKind.Utc).AddTicks(1344))
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.CompanyGeolocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<Point>("Coord")
                        .IsRequired()
                        .HasColumnType("point")
                        .HasColumnName("coord");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("int")
                        .HasColumnName("radius_meters");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("company_geolocation", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("location", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1a9bfc6-c8e5-4f11-afb9-aa5d93a89aae"),
                            Name = "company"
                        },
                        new
                        {
                            Id = new Guid("a77ad8ef-d3e6-413b-a18e-3275643f68e3"),
                            Name = "employee"
                        },
                        new
                        {
                            Id = new Guid("25154d0f-7a14-4c2a-93ee-649c5c12dede"),
                            Name = "work"
                        });
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 5, 21, 11, 28, 22, 37, DateTimeKind.Utc).AddTicks(6884))
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("action_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("location_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 5, 21, 11, 28, 22, 38, DateTimeKind.Utc).AddTicks(5065))
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("plan_name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.SubscriptionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 5, 21, 11, 28, 22, 38, DateTimeKind.Utc).AddTicks(9460))
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("subscription_events", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 5, 21, 11, 28, 22, 39, DateTimeKind.Utc).AddTicks(3412))
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EmployeeSignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("employee_signed_at");

                    b.Property<DateTime?>("HRSignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hr_signed_at");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<bool>("SignedByEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("signed_by_employee");

                    b.Property<bool>("SignedByHR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("signed_by_hr");

                    b.Property<Guid?>("SignedByHRUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("signed_by_hr_user_id");

                    b.Property<string>("SignedByHRUserName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("signed_by_hr_user_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_time_sheet_user_month_year");

                    b.ToTable("time_sheet", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Cellphone")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cellphone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2026, 5, 21, 11, 28, 22, 40, DateTimeKind.Utc).AddTicks(7295))
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAllowedBypassCoord")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_allowed_by_pass_coord");

                    b.Property<bool>("IsAllowedBypassFacial")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_allowed_bypass_facial");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_confirmed");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Point>("Coord")
                        .IsRequired()
                        .HasColumnType("point")
                        .HasColumnName("coord");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<bool>("IsLate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_late");

                    b.Property<string>("Justification")
                        .HasColumnType("longtext")
                        .HasColumnName("justification");

                    b.Property<string>("Observation")
                        .HasColumnType("longtext")
                        .HasColumnName("observation");

                    b.Property<DateTime>("PunchTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("punch_time");

                    b.Property<string>("PunchType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("punch_type");

                    b.Property<int>("ShiftType")
                        .HasColumnType("int")
                        .HasColumnName("shift_type");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<TimeOnly?>("TimeLate")
                        .HasColumnType("time(6)")
                        .HasColumnName("time_late");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_attendance", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserAuth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("refresh_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_auth", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("FaceTemplate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_face", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("char(36)")
                        .HasColumnName("shift_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("user_shift", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.WorkShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shift_type");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("starter_time");

                    b.Property<int>("ToleranceMinutes")
                        .HasColumnType("int")
                        .HasColumnName("tolerance_minutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("work_shift", (string)null);
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Company", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Address", "Address")
                        .WithOne("Company")
                        .HasForeignKey("DeltaFour.Domain.Entities.Company", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Address");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.CompanyGeolocation", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithOne("CompanyGeolocation")
                        .HasForeignKey("DeltaFour.Domain.Entities.CompanyGeolocation", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Role", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Action", "Action")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeltaFour.Domain.Entities.Location", "Location")
                        .WithMany("RolePermissions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeltaFour.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Location");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithOne("Subscription")
                        .HasForeignKey("DeltaFour.Domain.Entities.Subscription", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.SubscriptionEvent", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionEvents")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.TimeSheet", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.User", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithMany("User")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeltaFour.Domain.Entities.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId");

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserAttendance", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithMany("UserAttendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserAuth", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithOne("UserAuth")
                        .HasForeignKey("DeltaFour.Domain.Entities.UserAuth", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserFace", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithMany("UserFaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.UserShift", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.WorkShift", "WorkShift")
                        .WithMany("UserShifts")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeltaFour.Domain.Entities.User", "User")
                        .WithMany("UserShifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.WorkShift", b =>
                {
                    b.HasOne("DeltaFour.Domain.Entities.Company", "Company")
                        .WithMany("WorkShifts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Action", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Address", b =>
                {
                    b.Navigation("Company");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Company", b =>
                {
                    b.Navigation("CompanyGeolocation");

                    b.Navigation("Roles");

                    b.Navigation("Subscription");

                    b.Navigation("User");

                    b.Navigation("WorkShifts");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Location", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("SubscriptionEvents");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.User", b =>
                {
                    b.Navigation("UserAttendances");

                    b.Navigation("UserAuth");

                    b.Navigation("UserFaces");

                    b.Navigation("UserShifts");
                });

            modelBuilder.Entity("DeltaFour.Domain.Entities.WorkShift", b =>
                {
                    b.Navigation("UserShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
